/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package flowtrabajar;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class FPrincipal extends javax.swing.JFrame {
    private int[] numeros; // Cambiado a un arreglo unidimensional en lugar de una matriz bidimensional

    // Resto del código de tu clase...

    public FPrincipal() {
        initComponents();
        setLocationRelativeTo(this);
        numeros = new int[10]; // Inicializar el arreglo aquí o en algún otro lugar adecuado
    }

    // Re

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bOrdenarArray = new javax.swing.JButton();
        bParesImpares = new javax.swing.JButton();
        bMediana = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bOrdenarArray.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bOrdenarArray.setText("Ordenar Array");
        bOrdenarArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdenarArrayActionPerformed(evt);
            }
        });

        bParesImpares.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bParesImpares.setText("Pares e impares");
        bParesImpares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bParesImparesActionPerformed(evt);
            }
        });

        bMediana.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bMediana.setText("Mediana");
        bMediana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMedianaActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(437, Short.MAX_VALUE)
                .addComponent(bOrdenarArray)
                .addGap(253, 253, 253)
                .addComponent(bMediana)
                .addGap(61, 61, 61))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(bParesImpares)
                    .addContainerGap(808, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOrdenarArray)
                    .addComponent(bMediana))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(bParesImpares)
                    .addContainerGap(429, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bParesImparesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bParesImparesActionPerformed
  for (int i = 0; i < 10; i++) {
        String input = JOptionPane.showInputDialog(this, "Escribe el numero " + i);
        if (input == null) {
            // El usuario ha pulsado el botón de cancelar
            return;
        }
        try {
            numeros[i] = Integer.parseInt(input);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error: Debes ingresar un número válido.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
            return; // Sale del método si se produce una excepción
        }
    }
    jTextArea1.append("\nPares e impares\n----------------------------------\n");
    try {
        mostrar(paresImparess.mostrarParesImpares(numeros));
    } catch (NegativoException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_bParesImparesActionPerformed

    private void bOrdenarArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdenarArrayActionPerformed
         String input = JOptionPane.showInputDialog(this, "Escribe los numeros del array separados con espacios\n ej:2 45 8 9");
    if (input == null) {
        // El usuario ha pulsado el botón de cancelar
        return;
    }
    if (input.isBlank()) {
        JOptionPane.showMessageDialog(this, "No has introducido numeros", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    jTextArea1.append("\nOrdenar array\n----------------------------------\n");
    try {
        mostrar(ordenaArray.ordenaArray(input) + "\n");
    } catch (NegativoException ex) {
        JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        return; // Sale del método si se produce una excepción
    }
    }//GEN-LAST:event_bOrdenarArrayActionPerformed

    private void bMedianaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMedianaActionPerformed
         for (int i = 0; i < 10; i++) {
        String input = JOptionPane.showInputDialog(this, "Escribe el numero " + i);
        if (input == null) {
            // El usuario ha pulsado el botón de cancelar
            return;
        }
        try {
            numeros[i] = Integer.parseInt(input);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Error: Debes ingresar un número válido.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
            return; // Sale del método si se produce una excepción
        }
    }
    jTextArea1.append("\nMediana\n----------------------------------\n");
    try {
        mostrar(mediana.mediana(numeros));
    } catch (NegativoException ex) {
        Logger.getLogger(FPrincipal.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_bMedianaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bMediana;
    private javax.swing.JButton bOrdenarArray;
    private javax.swing.JButton bParesImpares;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    private void mostrar(String texto){
    jTextArea1.append(texto);
}

}
